/**
 * Renders `registry/terminal/theme.mjs` into the two places the theme has to
 * exist: this site's stylesheet, and the `theme` item inside `registry.json`
 * that `shadcn add` merges into somebody else's.
 *
 * Both outputs are committed. They are generated rather than written so the
 * documentation site is painted with the same values it hands out. A registry
 * whose demo has drifted from its payload is worse than no demo.
 */

import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { css, cssVars } from "../registry/terminal/theme.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const GLOBALS = join(ROOT, "app", "globals.css");
const REGISTRY = join(ROOT, "registry.json");

const BANNER = `/**
 * Generated by scripts/build-globals.mjs from registry/terminal/theme.mjs.
 * Edit the theme, not this file: \`pnpm registry:build\` rewrites it.
 */`;

const INDENT = "  ";

/** A block whose values are all leaves, e.g. \`:root { --void: #05090a }\`. */
function renderDeclarations(entries, depth) {
  const pad = INDENT.repeat(depth);
  return entries.map(([prop, value]) => `${pad}${prop}: ${value};`).join("\n");
}

/**
 * Objects nest arbitrarily: `@layer base` holds selectors, selectors hold
 * declarations, `@keyframes` holds offsets which hold declarations. So the
 * renderer only has to know which of the two a value is.
 */
function renderBlock(node, depth) {
  const pad = INDENT.repeat(depth);
  const lines = [];
  const declarations = [];

  for (const [key, value] of Object.entries(node)) {
    if (value !== null && typeof value === "object") {
      if (declarations.length > 0) {
        lines.push(renderDeclarations(declarations.splice(0), depth));
      }
      lines.push(`${pad}${key} {\n${renderBlock(value, depth + 1)}\n${pad}}`);
    } else {
      declarations.push([key, value]);
    }
  }

  if (declarations.length > 0) {
    lines.push(renderDeclarations(declarations, depth));
  }

  return lines.join("\n");
}

/** Variable maps arrive without their leading dashes; every consumer adds them. */
function renderVariables(selector, variables) {
  const body = Object.entries(variables)
    .map(([name, value]) => `${INDENT}--${name}: ${value};`)
    .join("\n");
  return `${selector} {\n${body}\n}`;
}

const globals = [
  BANNER,
  '@import "tailwindcss";',
  renderVariables(":root", cssVars.light),
  renderVariables(".dark", cssVars.dark),
  renderVariables("@theme inline", cssVars.theme),
  ...Object.entries(css).map(
    ([key, value]) => `${key} {\n${renderBlock(value, 1)}\n}`
  ),
].join("\n\n");

await writeFile(GLOBALS, `${globals}\n`);

const registry = JSON.parse(await readFile(REGISTRY, "utf8"));
const theme = registry.items.find((item) => item.name === "theme");

if (!theme) {
  throw new Error(
    "registry.json has no item named 'theme' to write the tokens into."
  );
}

theme.cssVars = cssVars;
theme.css = css;

await writeFile(REGISTRY, `${JSON.stringify(registry, null, 2)}\n`);

process.stdout.write(
  `theme: ${Object.keys(cssVars.light).length} variables, ${Object.keys(css).length} css blocks\n`
);
